### ISSUE TITLE
Python and cross-spawn

### ISSUE THREAD

**Issue by kelvix** [IndigoUnited/node-cross-spawn-async#1]
Over at [atom-beautify](https://github.com/Glavin001/atom-beautify/issues/456) we appear to be having some trouble with sqlparse (sqlformat). The python script starts with

    #!C:\Python34\python.exe

    # Copyright (C) 2008 Andi Albrecht, albrecht.andi@gmail.com
    #
    # This module is part of python-sqlparse and is released under
    # the BSD License: http://www.opensource.org/licenses/bsd-license.php.

I think that I've concluded based on [readShebang](https://github.com/IndigoUnited/node-cross-spawn-async/blob/master/lib/parse.js#L9-L36) this python script never runs successfully due to the regex. I've been able to get the script to run by modifying the shebang

    #!/usr/bin/env C:\Python34\python.exe

The only downside of course is that python scripts by default don't work and require user changes. The script was installed using pip so I believe that all python scripts would be affected by this. Think it may be necessary to do a python check?

I only looked into ruby for an example of how they do things they seem to [ask users to add .rb to their PATHEXT](https://en.wikibooks.org/wiki/Ruby_Programming/Hello_world) or something of the sorts which does happen to cover our bases; however an out of the box solution needing no manual interventions would be great.

**Comment by satazor** [comment]
Thanks for the report, fixed in https://github.com/IndigoUnited/node-cross-spawn-async/commit/8c7fe6902c3dca829e89eeb412afb286058077c9

Launched 2.0.0 with the fix.
