### ISSUE TITLE
relative path to extension-less command doesn't read shebang?

### ISSUE THREAD

**Issue by tswaters** [IndigoUnited/node-cross-spawn-async#2]
I'm trying to get mocha's test suite working cross platform and I have a strange issue,

If I attempt to `spawn('./bin/mocha')` it doesn't read the shebang and I get `./bin/mocha is not recognized...` however, if I `spawn('bin/mocha')` it works properly. 

It looks like when I include a dot in the cmd, "./bin/mocha", [which will add a blank string to pathext](https://github.com/isaacs/node-which/blob/master/which.js#L62-L63) and ends up finding mocha.... but because the shebang is only read on the second pass, it doesn't work at all.

**Comment by satazor** [comment]
fixed in https://github.com/IndigoUnited/node-cross-spawn-async/commit/51e5611dd33c9e9f65e1f0649f81d1af3e19b2e2
