### ISSUE TITLE
Too many quotes, args: [ '/s', '/c', '""node ./fixtures/hello-server""' ]

### ISSUE THREAD

**Issue by fritx** [IndigoUnited/node-cross-spawn-async#3]
```plain
{ command: 'C:\\WINDOWS\\system32\\cmd.exe',
  args: [ '/s', '/c', '""serve . -p 3002""' ],
  options: { windowsVerbatimArguments: true },
  file: undefined,
  original: 'serve . -p 3002' }
3824
    1) serve .
{ command: 'C:\\WINDOWS\\system32\\cmd.exe',
  args: [ '/s', '/c', '""node ./fixtures/hello-server""' ],
  options: { windowsVerbatimArguments: true },
  file: undefined,
  original: 'node ./fixtures/hello-server' }
5932
    2) node hello-world
```

In Windows, the `lib/parse.js` seems to quote too many quotes, and made errors

```plain
Uncaught Error: spawn node ./fixtures/hello-server ENOENT
      at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
```

I disabled the following line of source code, and it began to work...
Any idea? thanks :smile: 

```js
// Quote the whole thing:
arg = '"' + arg + '"';
```

**Comment by shinnn** [comment]
@fritx How does your Node script look like?

**Comment by fritx** [comment]
@shinnn oh it's a too long time.. i can hardly pick up the code at that moment..
once i find i would paste it here :smile: thanks

**Comment by satazor** [comment]
@fritx I'm can look at this now, but I need more info regarding the command you are trying to run in the shell. Do you still have the command?

**Comment by satazor** [comment]
Well I'm going to close this. If you provide the node script you were running I will re-open it.
